FROM golang:1.17.0 AS builder

WORKDIR /src/
ENV CGO_CFLAGS="-Wno-return-local-addr"
COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bullseye
EXPOSE 3000 4000

WORKDIR /app/
COPY --from=builder /app/webapi ./

CMD ["/app/webapi"]