version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:3000"   # host:container  -> backend reachable at http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/liveness"]
      interval: 5s
      timeout: 2s
      retries: 10
