FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
WORKDIR /app/cmd/server
RUN go build -o /server .
FROM alpine:3.20
WORKDIR /app
COPY --from=build /server .
EXPOSE 8080
CMD ["/app/server"]
