version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"   # API → http://localhost:8080

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8081:80"     # Web → http://localhost:8081"
