name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install validators
        run: |
          python -m pip install --upgrade pip
          pip install openapi-spec-validator prance
      - name: Validate OpenAPI
        run: |
          python -m openapi_spec_validator doc/api.yaml
          python - << 'PY'
          from prance import ResolvingParser
          ResolvingParser("doc/api.yaml")
          print("Prance OK")
          PY

  python-tests:
    runs-on: ubuntu-latest
    needs: validate-openapi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest (backend)
        working-directory: backend
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
        run: pytest -q

  build-go:
    runs-on: ubuntu-latest
    needs: validate-openapi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Go backend
        working-directory: backend
        run: go build -v -o server main.go
